### ISSUE TITLE
Investigate stress-ng usage

### ISSUE THREAD

**Issue by ArsenyBochkarev** [Compiler-assisted-fuzzing/llvm-project#13]
Build and run tests from [stress-ng](https://github.com/ColinIanKing/stress-ng). Investigate how to add our custom option to build. List below:
- Simple tutorial on how to build, set options and run tests
- Any useful options for configuring/building tests for L1I, BPU, or any other CPU component
- Optionally other notes on user experience

**Comment by dmittrey** [comment]
make clean
STATIC=1 CC=mips64-linux-gnuabi64-gcc CXX=mips64-linux-gnuabi64-g++ make -j $(nproc)

**Comment by dmittrey** [comment]
Удалось загрузить Debian пакет stress-ng 
stress-ng, version 0.15.08 (gcc 12.2.0, riscv64 Linux 5.10.113-th1520) 💻🔥

Caches:
-C N, --cache N             start N CPU cache thrashing workers
      --cache-enable-all    enable all cache options (fence,flush,sfence,etc..)
      --cache-fence         serialize stores
      --cache-level N       only exercise specified cache
      --cache-no-affinity   do not change CPU affinity
      --cache-ops N         stop after N cache bogo operations
      --cache-prefetch      prefetch on memory reads/writes
      --cache-ways N        only fill specified number of cache ways
      --cache-wb            cache line writeback (x86 only)
      --cacheline N         start N workers that exercise cachelines
      --cacheline-affinity  modify CPU affinity
      --cacheline-method M  use cacheline stressing method M
      --cacheline-ops N     stop after N cacheline bogo operations

L1:
--l1cache N           start N CPU level 1 cache thrashing workers
      --l1cache-line-size N specify level 1 cache line size
      --l1cache-sets N      specify level 1 cache sets
      --l1cache-size N      specify level 1 cache size
      --l1cache-ways N      only fill specified number of cache ways
      --l1cache-method M    l1 cache thrashing method: forward, reverse, random
BPU:
      --branch N            start N workers that force branch misprediction
      --branch-ops N        stop after N branch misprediction branches
      --far-branch N        start N far branching workers
      --far-branch-ops N    stop after N far branching bogo operations
      --goto N              start N workers that exercise heavy branching
      --goto-direction D    select goto direction forward, backward, random
      --goto-ops N          stop after 1024 x N goto bogo operations
      
Instruction caches specifically:
      --flushcache N          start N CPU instruction + data cache flush
      --icache N              start N CPU instruction cache thrashing workers

**Comment by dmittrey** [comment]
Могу завести задачу чтобы нашим компилятором собирать stress-ng и пробовать запускать по всем ключам.

@ArsenyBochkarev Что думаешь?

**Comment by dmittrey** [comment]
Закинуть пример

**Comment by dmittrey** [comment]
debian@revyos-lpi4a:~$ stress-ng --branch 10 --timeout 10s
stress-ng: info:  [839] setting to a 10 second run per stressor
stress-ng: info:  [839] dispatching hogs: 10 branch
stress-ng: info:  [839] passed: 10: branch (10)
stress-ng: info:  [839] failed: 0
stress-ng: info:  [839] skipped: 0
stress-ng: info:  [839] successful run completed in 10.12s

debian@revyos-lpi4a:~$ stress-ng --cache 4 --timeout 10s
stress-ng: info:  [858] setting to a 10 second run per stressor
stress-ng: info:  [858] dispatching hogs: 4 cache
stress-ng: info:  [859] cache: cache flags used: prefetch clflush fence sfence clflushopt cldemote clwb
stress-ng: info:  [858] passed: 4: cache (4)
stress-ng: info:  [858] failed: 0
stress-ng: info:  [858] skipped: 0
stress-ng: info:  [858] successful run completed in 10.02s

**Comment by ArsenyBochkarev** [comment]
Please use our fork of stress-ng: https://github.com/Compiler-assisted-fuzzing/stress-ng -- I faced compilation error when cross-compiling for RISC-V with our flags, which I resolved with this [commit](https://github.com/Compiler-assisted-fuzzing/stress-ng/commit/e269f796977277e6064fbb035687ea0451f8143b). The full instruction is:

- `export CFLAGS="--target=riscv64-unknown-linux-gnu --gcc-toolchain=<path to GCC> --sysroot=<path to GCC>/sysroot/ --fuzz=<your fuzzing flags>"`
- `export CC="<path to clang>"`
- `export CXX="<path to clang++>"`
- `make clean`
- `STATIC=1 make -j$(nproc)`

In order to create a debug build of stress-ng, add the `DEBUG=1` to `make` command
