### ISSUE TITLE
L1I: Randomly shuffle machine basic blocks across generated binary

### ISSUE THREAD

**Issue by ArsenyBochkarev** [Compiler-assisted-fuzzing/llvm-project#16]
We need to fuzz L1I caches by randomly shuffling machine basic blocks. We should write our custom LLVM pass for this purpose. The pass should be placed right after the MBB placement pass, so that our efforts won't be optimized away.

Please refer to [this](https://llvm.org/docs/WritingAnLLVMNewPMPass.html) document before you begin.

**Comment by dee-tree** [comment]
Achieved result:

![image](https://github.com/user-attachments/assets/f4d81a42-3395-420c-a313-ab1eb38040da)
![image](https://github.com/user-attachments/assets/e996395b-f134-4055-aa3b-eb2da92df013)
