### ISSUE TITLE
Fuzz Machine Block Placement pass

### ISSUE THREAD

**Issue by ArsenyBochkarev** [Compiler-assisted-fuzzing/llvm-project#2]
You'll need to "break" LLVM's [MBB placement](https://github.com/llvm/llvm-project/blob/main/llvm/lib/CodeGen/MachineBlockPlacement.cpp) predicatively. The high-level steps are:
- Read the [wiki page](https://github.com/Compiler-assisted-fuzzing/llvm-project/wiki/Compiler%E2%80%90assisted-fuzzing-guidelines) for guidelines on how to do it
- Use a BPU component (which should be shipped in our LLVM fork)
- Possibly invert all of the probabilities predicatively
- Verify your changes do something:
  - use any test from LLVM or use any of the benchmarks listed [here](https://github.com/Compiler-assisted-fuzzing/llvm-project/issues/1) 
  - Compile it with and without `--fuzz=bpu` option. Make sure to use the RISC-V toolchain
  - Compare the output using `objdump -d` (don't forget to use objdump for RISC-V!) or LLVM IR output
- Possible extra task: research on whether we can shuffle machine basic blocks automatically

*Tip on how to find proper LLVM test: grep for "block-placement" (which is essentially just the `DEBUG_TYPE` for this pass).*

**Comment by ArsenyBochkarev** [comment]
Possible extra task: research on whether we can shuffle machine basic blocks automatically

**Comment by dee-tree** [comment]
# Machine basic block placement
- [Article on branch prediction technics + llvm PGO](https://www.diva-portal.org/smash/get/diva2:1450658/FULLTEXT01.pdf).
- [PGO in llvm](https://llvm.org/devmtg/2013-11/slides/Carruth-PGO.pdf).
- [PGO llvm in action](https://llvm.org/devmtg/2020-09/slides/PGO_Instrumentation.pdf).

# How to trigger machine block placement pass?

## Variant 1: dynamic PGO
1. Compile binary that will be profiled: `clang -fprofile-instr-generate -fcoverage-mapping <code.c> -o <code.out>`
2. Run binary to collect data (more times => more honest): `./<code.out>` => `default.profraw` will be generated.
3. Merge collected profile data: `llvm-profdata merge default.profraw -o <code.profdata>`
4. Recompile the code using profile data: `clang -fprofile-instr-use=<code.profdata> -OX -S -o <code.s> <code.c>` to get assembly code with optimization applied (or emit llvm IR using `-emit-llvm` and get stats inside (such as branches probabilities).

## Variant 2: Based on static analysis / assist

1. (Optional) you could call builtin to specify if one branch is more often than other: `__builtin_expect(condition, <expected_branch_bool>)` such as `__builtin_expect(a + a > a, 1)`.
2. Emit asm: `clang -OX -S <code.c> -o <code.s>`.

## Variant 3: Trigger it on MIR
1. Emit llvm IR: `clang -O0 -S -emit-llvm <code.c>`
2. Emit llvm MIR: `llc -O0 <code.ll> --stop-before=block-placement -o <code.mir>`
3. Apply pass on MIR: `llc -O0 --run-pass=block-placement <code.mir> -o <code.opt.mir>`
  - add more visual options: `--run-pass=block-placement-stats,branch-prob -print-bpi` (and `--stats` if it enabled)

Note: Use `-O0` exactly. The pass will trigger and the experiment will be clear due to lack of other optimizations.

**Comment by dee-tree** [comment]
> # How to trigger machine block placement pass?
> ...
> ## Variant 3: Trigger it on MIR
> 1. Emit llvm IR: `clang -O1 -S -emit-llvm <code.c>`
> 2. Emit llvm MIR: `llc -O1 <code.ll> --stop-before=block-placement -o <code.mir>`
> 3. Apply pass on MIR: `llc -O0 --run-pass=block-placement <code.mir> -o <code.opt.mir>`
>  - add more visual options: `--run-pass=block-placement-stats,branch-prob -print-bpi` (and `--stats` if it enabled)
>
> Note: Use `-O0` exactly. The pass will trigger and the experiment will be clear due to lack of other optimizations.

Applying it on MIR:

For IR:
```llvm-ir
  @a = external global i16
  @b = external global i32

  declare void @foo()
  declare void @dummy2()
  declare void @dummy3()

  ; Function Attrs: nounwind
  define void @f2() {
    br i1 undef, label %bb1, label %bb3

  bb1:
    call void @foo()
    br i1 undef, label %bb2, label %bb2

  bb2:
    call void @foo()
    br label %bb4

  bb3:
    call void @foo()
    br label %bb2

  bb4:
    ret void
  }
```

and its MIR (without optimizations):

```llvm-mir
--- |
  ; ModuleID = 'test.ll'
  source_filename = "test.ll"
  
  @a = external global i16
  @b = external global i32
  
  declare void @foo()
  declare void @dummy2()
  declare void @dummy3()
  
  define void @f2() {
    br i1 undef, label %bb1, label %bb3
  
  bb1:                                              ; preds = %0
    call void @foo()
    br i1 undef, label %bb2, label %bb2
  
  bb2:                                              ; preds = %bb3, %bb1, %bb1
    call void @foo()
    br label %bb4
  
  bb3:                                              ; preds = %0
    call void @foo()
    br label %bb2
  
  bb4:                                              ; preds = %bb2
    ret void
  }

...

body:             |
  bb.0 (%ir-block.0):
    frame-setup PUSH64r undef $rax, implicit-def $rsp, implicit $rsp
    frame-setup CFI_INSTRUCTION def_cfa_offset 16
    renamable $al = IMPLICIT_DEF
    TEST8ri killed renamable $al, 1, implicit-def $eflags
    JCC_1 %bb.1, 5, implicit killed $eflags
    JMP_1 %bb.3
  
  bb.1.bb1:
    CALL64pcrel32 target-flags(x86-plt) @foo, csr_64, implicit $rsp, implicit $ssp
    renamable $al = IMPLICIT_DEF
    TEST8ri killed renamable $al, 1, implicit-def $eflags
    JCC_1 %bb.2, 5, implicit killed $eflags
  
  bb.2.bb2:
    CALL64pcrel32 target-flags(x86-plt) @foo, csr_64, implicit $rsp, implicit $ssp
    JMP_1 %bb.4
  
  bb.3.bb3:
    CALL64pcrel32 target-flags(x86-plt) @foo, csr_64, implicit $rsp, implicit $ssp
    JMP_1 %bb.2
  
  bb.4.bb4:
    $rax = frame-destroy POP64r implicit-def $rsp, implicit $rsp
    frame-destroy CFI_INSTRUCTION def_cfa_offset 8
    RET64
```

And optimized MIR via `llc --run-pass=block-placement,block-placement-stats,branch-prob test.mir -o test.opt.mir --stats -print-bpi`:

```llvm-mir
--- |
  ; ModuleID = 'test.mir'
  source_filename = "test.ll"
  ; ### No difference here, because it's an unused copy of IR just for matching with MIR. Look below, please, under body. 
  @a = external global i16
  @b = external global i32
  
  declare void @foo()
  declare void @dummy2()
  declare void @dummy3()
  
  define void @f2() {
    br i1 undef, label %bb1, label %bb3
  
  bb1:                                              ; preds = %0
    call void @foo()
    br i1 undef, label %bb2, label %bb2
  
  bb2:                                              ; preds = %bb3, %bb1, %bb1
    call void @foo()
    br label %bb4
  
  bb3:                                              ; preds = %0
    call void @foo()
    br label %bb2
  
  bb4:                                              ; preds = %bb2
    ret void
  }

...

body:             |
  bb.0 (%ir-block.0):
    successors: %bb.1(0x40000000), %bb.3(0x40000000)
  
    frame-setup PUSH64r undef $rax, implicit-def $rsp, implicit $rsp
    frame-setup CFI_INSTRUCTION def_cfa_offset 16
    renamable $al = IMPLICIT_DEF
    TEST8ri killed renamable $al, 1, implicit-def $eflags
    JCC_1 %bb.3, 4, implicit $eflags
  
  bb.1.bb1:
    successors: %bb.2(0x80000000)
  
    CALL64pcrel32 target-flags(x86-plt) @foo, csr_64, implicit $rsp, implicit $ssp
    renamable $al = IMPLICIT_DEF
    TEST8ri killed renamable $al, 1, implicit-def $eflags
  
  bb.2.bb2:
    successors: %bb.4(0x80000000)
  
    CALL64pcrel32 target-flags(x86-plt) @foo, csr_64, implicit $rsp, implicit $ssp
  
  bb.4.bb4:
    $rax = frame-destroy POP64r implicit-def $rsp, implicit $rsp
    frame-destroy CFI_INSTRUCTION def_cfa_offset 8
    RET64
  
; ### BB 3 was moved to the bottom as not optimal solution
  bb.3.bb3:
    successors: %bb.2(0x80000000)
  
    CALL64pcrel32 target-flags(x86-plt) @foo, csr_64, implicit $rsp, implicit $ssp
    JMP_1 %bb.2
...

```

And, for comparison, correctly optimized version:
```llvm-mir
--- |
  ; ModuleID = 'test.mir'
  source_filename = "test.ll"
  
  @a = external global i16
  @b = external global i32
  
  declare void @foo()
  declare void @dummy2()
  declare void @dummy3()
  
  define void @f2() {
    br i1 undef, label %bb1, label %bb3
  
  bb1:                                              ; preds = %0
    call void @foo()
    br i1 undef, label %bb2, label %bb2
  
  bb2:                                              ; preds = %bb3, %bb1, %bb1
    call void @foo()
    br label %bb4
  
  bb3:                                              ; preds = %0
    call void @foo()
    br label %bb2
  
  bb4:                                              ; preds = %bb2
    ret void
  }

...

body:             |
  bb.0 (%ir-block.0):
    successors: %bb.1(0x40000000), %bb.3(0x40000000)
  
    frame-setup PUSH64r undef $rax, implicit-def $rsp, implicit $rsp
    frame-setup CFI_INSTRUCTION def_cfa_offset 16
    renamable $al = IMPLICIT_DEF
    TEST8ri killed renamable $al, 1, implicit-def $eflags
    JCC_1 %bb.3, 4, implicit $eflags
  
  bb.1.bb1:
    successors: %bb.2(0x80000000)
  
    CALL64pcrel32 target-flags(x86-plt) @foo, csr_64, implicit $rsp, implicit $ssp
    renamable $al = IMPLICIT_DEF
    TEST8ri killed renamable $al, 1, implicit-def $eflags
    JMP_1 %bb.2
  ; ### Pay attention that block 3 and 2 were swapped as optimal solution
  bb.3.bb3:
    successors: %bb.2(0x80000000)
  
    CALL64pcrel32 target-flags(x86-plt) @foo, csr_64, implicit $rsp, implicit $ssp
  
  bb.2.bb2:
    successors: %bb.4(0x80000000)
  
    CALL64pcrel32 target-flags(x86-plt) @foo, csr_64, implicit $rsp, implicit $ssp
  
  bb.4.bb4:
    $rax = frame-destroy POP64r implicit-def $rsp, implicit $rsp
    frame-destroy CFI_INSTRUCTION def_cfa_offset 8
    RET64

...

```

**Comment by dee-tree** [comment]
BTW, sometimes it could be useful to get branch probabilities block placement pass uses. To achieve it:
+ run passes `branch-prob` and `block-placement-stats` together with `block-placement`.
+ use`--stats` and `-debug` options to llc when possible.
