### ISSUE TITLE
LicheePi bring-up & research

### ISSUE THREAD

**Issue by ArsenyBochkarev** [Compiler-assisted-fuzzing/llvm-project#7]
You'll need to research on how to bring-up the LicheePi RISC-V board. The high-level steps are:
- From LicheePi specifications learn about protection mode for Linux (`S` or `M`)
  - If it is `M`: nothing here, bring-up normally
  - If it is `S`: create a module so that we'll be able to poll CSR registers at the same time the fuzzed project is run
- Boot Linux on board

**Comment by dmittrey** [comment]
Assemble by Buildroot Linux Image for Lichee Pi 4A

Buildroot Image for TH1520(SoC)
https://github.com/lone0/buildroot-th1520

https://github.com/AdvancedClimateSystems/docker-buildroot

Now we can access Lichee by ssh in local network, now working with ssh tunnel to have access for other members of team

**Comment by ArsenyBochkarev** [comment]
Please also add ssh connection

**Comment by dmittrey** [comment]
Burn official Debian Image kernel v5.10
https://wiki.sipeed.com/hardware/en/lichee/th1520/lpi4a/3_images.html

Also Added ssh connection over vpn

Lichee - 10.8.0.2
D. Zubakhin - 10.8.0.3
A. Bochkarev - 10.8.0.4
D. Tolmachev - 10.8.0.5
D. Sokolov - 10.8.0.6

**Comment by dmittrey** [comment]
Информации по регистрам ни в каких мануалах не нашел.

Также была информация по поводу perf-counters, но также ничего найдено не было.

Пока идей нету

**Comment by dmittrey** [comment]
https://git.beagleboard.org/beaglev-ahead/beaglev-ahead/-/tree/main/docs?ref_type=heads

https://github.com/jdmccalpin/periodic-performance-counters
